import java.io.*;
import java.util.*;
import java.awt.*;
import hsa.Console;

public class initializeVariables {
    static String globText[][] = 
		{
			{
				"WAIT",
				"Seven boys and seven girls, lined up under the hazy sun.\n\nWeaponless, defenseless. Which death for these youth would be worse; devoured by a half-man beast, or starved in a lightless corner?\n\nThe threads of fate were to run bare today, is what the others presumed. But you have a plan. The bloody tributes have continued for too long.\n\nA fool's plan, not untried before; yet even the bravest of warriors had failed. Will you be the one to complete it?\n\nYour tunic is heavy, the sheathed sword underneath warming uncomfortably in the heat. You shift it a bit to prevent the guards from noticing.\n\nThis beast, this supposed monster with a bull's head, how will it act? Will it be possible to speak reason with it? It is, after all, half man. You reprimand yourself with a pinch; be more concerned about how to survive the journey first.",
				"And so it begins. The guards shove you forward. You shove yourself forward before your temper can strike out. Remember, weaponless, defenseless, a sacrifice to something higher. Sacrifices do not fight back.\n\nAlone, you are escorted to an entrance. You wonder if you will see the boy who was beside you again.\n\nThe iron doors groan, then scream, then snap shut decisively. You are alone now, but you must continue. How is it that the chill of the dark air can freeze your skin such that the faint warmth of the weak torch feels like a bonfire?\n\nThe walls seem to perspire, as if they share your fears. Regret is a friend who is too far away. If nothing else smolders your determination, terror will.",
				"After a bend, you arrive at your first challenge.\n\nTo the right, a branch in the caverns: the sputtering torch in your hands does nothing but amplify the shadows of the opening. The air feels damper, somehow, when you step inside.\n\nThe torch's halo dims, and you cling to the walls. One misstep could lead to a plummeting fall, or even just a sprain. You need to be very, very careful from now on, including in your decisions.",
				"Which path do you take?\n\tContinue straight (enter 1)\n\tTurn right (enter 2)\n"
			},
			{
				"END",
				"You continue forward. It'd be best to not take too many risks, right?\n\nWrong.\n\nYour foot catches a wire, and you tumble over the hidden trap. It creaks and groans, and you scramble to your feet. Something's gone wrong. Gears shift around and scream. You bolt back the direction you came from, but the slippery ground doesn't allow for it.\n\nSomething cold and heavy lands on your neck. There's a crack before your body is left behind in this depressing mortal plane.",
				"THE END"
			},
			{
				"WAIT",
				"Careful, careful. Tiny treads forward. A tap on the ground before a step. Reach forward to shed some light. The mantra rings in your head.\n\nYour strategy proves useful when your toe sweeps air instead of stone. It shakes your balance only slightly, and you grip onto a prickly, damp wooden railing. Your torch reveals a gap in your path; a narrow river, deep and violent, bashing against the walls it carved like a bull.\n\nThere is a bridge, but years have rotted the planks and frayed the ropes. Some pieces still appear salvageable though, and a bit of handiwork should be able to sustain your crossing.\n\nFrom your hand, the rope fastens into a series of knots, the dangling pieces linking to form a makeshift tightrope. Of course, you won’t be able to walk across it, but you can crawl.",
				"You toss your belongings over. This rope might not be able to hold an adult person and a metal sword.\n\nClinging to the cord, you shift across. The splashing and crashing of the river below tries to unsettle you. It sounds like a bull too. You can’t be frightened by this. What would you do when you face the real bull?",
				"The last fragment of rope is a bit thinner, chewed away by mold and water. So close to the other side, you grip the last section, then haul yourself onto solid land.\n\nThe rope snaps once your weight shifts. You manage to pull yourself onto the other side. The snake sways and lashes against the rocks, furious at your betrayal. You are a little sad yourself; that rope would've been quite useful.\n\nAlas, the journey continues.",
				"You can almost feel the trajectory of the sun as you're stuck in what feels like an endless series of stairs and corridors. The sound of your footsteps becomes unbearable. The darkness hugs closer as your torch fades.\n\nIt feels like winter by the time you reach another crossroads, quite literally. You stumble into the wall in front of you and sink to the floor, too tired and cold to make a decision. You set your torch aside and rub your hands, as if you could start a fire with them.\n\nThere are two doors this time. You press your palm to the rotting wood of the left. It's vibrating; perhaps something alive is behind it. If it's an animal, it could mean food. The right door is bronze, heavy to open; it's warm to the touch, and you're almost tempted to fling it open right then and there.",
				"Knowing the genius of the designer, you likely won't be able to turn back. Which door do you open?\n\tThe bronze door (enter 3)\n\tThe wooden door (enter 4)"
			},
			{
				"END",
				"The door locks behind you, like it did when you first entered the labyrinth. Sometimes, you muse, man's inventions really can work like magic.\n\nThere's something burning behind this door. It's apparent as soon as you step in by the smoky aroma and the shadows being casted on the wall.\n\nLight. Fire.\n\nYou don't know where it's coming from, but it's certainly somewhere. You strain your ears for the sound of a crackle.\n\nThe air starts to choke your lungs, and the soot gathers on your skin. You need an exit, now.",
				"You forget where your feet lead you, but you only run into dead ends. You move faster and breathe heavier; more soot in your chest.\n\nThere's no need to search for the fire anymore; it's everywhere. You sink into the heat.\n\nQuite morbidly, you recall your comparison of being a human sacrifice; it seems that was quite an accurate image.",
				"THE END"
			},
			{
				"WAIT",
				"The door locks behind you, like it did when you first entered the labyrinth. Sometimes, you muse, man's inventions really can work like magic.\n\nUnfortunately, there's no magic that can help you with the task ahead.\n\nThere's... something in the darkness. You can't really see it, but you can definitely hear it. It growls and snarls. You can almost imagine the teeth it'll have.\n\nYou draw your sword and hold it in front of you, ready to face your foe.",
				"It's a bear, that much is apparent once his claws strike the ground next to you. You try to maintain your form as you tumble back and dodge its blows. It wouldn't do well to be thrown off balance.\n\nIts teeth are glaringly bright, even when light is mostly absent; tiny slivers ready to grip your flesh. How they managed to keep a bear alive in here is beyond you. Maybe they invented some other contraption to go with this engineering feat. You jab your sort to keep the bear's claws away from your arms.\n\nThe fight is the fastest you've moved since you boarded the ship. You're out of shape, and it's increasingly difficult to keep up with the bear's attacks. There's no chance for you to win on speed and strength alone; battles are as much a test of mental capability, you remind yourself.",
				"Your torch lies not far away, sputtering gently. You lead the fight towards it, tiny steps backward in its direction. The claws of the bear graze your calf, a tiny cut, but the jolt of sudden pain sends you falling. You take the opportunity to scoop the torch and stick it at the bear's face.\n\nIt roars in pain, distracted by the heat for a moment, and your sword pierces it's throat. Dark red, like wine, the blood leaks from its neck, staining fur and skin alike. You shove it away while it's still thrashing, and keep your distance until its last jerks of movement have ceased.",
				"It smells like blood. The smell of something edible kindles your appetite, no matter how disgusting that something is. You haven't had a proper meal with the meager rations on the ship, and the Creteans hardly provided you and the youth with enough food to make up for it. Your muscles give away, weak from disuse.\n\nUsing your sword, you tear a chunk from the bear's leg. This is flesh, dripping with blood, not meat, but you force yourself to stomach the metallic taste. You'll need the energy.\n\nYour torch was extinguished in the fight, and the pitch black of the labyrinth, echoing with the screams of battle, begins to remind you of stories of the underworld.",
				"The fatigue in your bones cannot be banished with some rest, so you decide to sleep. There doesn't appear to be anything else threatening you. Before you drift away into your dreams, you skin the bear to the best of your abilities, and wrap the hide around you as a blanket. There may be bits of flesh and blood stains all over, and the smell is frankly putrid, but it keeps you warm in the absence of fire.",
				"The soreness in your body doesn't dissipate when you wake up, but you are less tired than before. You pull your makeshift fur cloak closer, and wonder how to navigate the maze without light. You decide to use your sword as a walking stick of sorts, and forge on forward.\n\nAfter some time, your sword hits a wall with a twang, and the paths diverge once more. Without sight, you can't quite notice any differences. Looks like you'll just have to leave it to luck this time.",
				"Which path do you pick?\n\tThe path to the left (enter 5)\n\tThe path to the right (enter 6)\n"
			},
			{
				"END",
				"You stumble to your left and hope for the best.\n\nWhat would happen if you misstep? You try not to entertain that idea, but in the darkness, one can never be sure.\n\nWhat if there's a snake? Or another bear? Or a trap? Your breathing quickens, and you stop for a moment to calm yourself.",
				"You have a sudden urge to scream into the darkness. The darkness screams back, with all the agony and desperation of yourself.\n\nThe echoes fall still, and the ensuing silence feels even lonelier.\n\nBut you're not alone.",
				"Silently, in the dark, a crafty weaver has strung her trap, and you don't even notice you've fallen in until you see stars in the darkness.\n\nYou collapse in a feverish trance, and the darkness swallows you as one of her own.",
				"THE END"
			},
			{
				"WAIT",
				"You stumble to your right and wish yourself good luck.\n\nSo far, this must've been the longest stretch you've walked, or perhaps it's the pitch black that wraps and warps your sense of time. Or perhaps it's the slower pace you walk at now, permanently alert for the hint of any predators.\n\nThe night of sleep has only brought out pains in your body that were masked by excitement, and your feet feel like they were wrapped in heavy chains. \n\nBut warriors conquer, and no chains can hinder that. You haul them up by their ends and imagine tossing them to the side. Your feet don't stop hurting, but you shoulder on, new determination in your bones.",
				"Is that the faint glow of light ahead?\n\nYou grip the wall to keep your feet from dashing forward in delight. You must approach with caution.\n\nIt hurts a bit to finally see again, but the sight that greets you is not much of a relief. An iron grille lined with braziers blocks your path, with a complex lock that won't budge under your sword.\n\nBut at least a riddle means a correct path, right?",
				"PUZZLE",
				"The door unlocks, and you heave it open. The path ahead opens its arms and you gladly accept its embrace. Every challenge you defeat brings new vigour to your heart.\n\nBefore leaving, you take the remnants of your old torch and light it in the braziers. It roars to life, and you allow yourself a smile as the world goes bright again. \n\nThe wide berth of the path narrows eventually into a corridor barely one man wide, but you squeeze through, back against the wall, trying not to burn your face on the torch, or accidentally poke yourself with your sword.\n\nYou nearly fall over when the stone behind you gives away to nothingness.",
				"There's a path emptying to the left, and by the looks of it, it's much wider than this suffocating place. You rub an area where your skin has been chafed raw, and you stare down these two choices again. After so much time without sun, the seemingly endless darkness of the side path doesn't look inviting, but with a torch, you suppose there's no need to fear it. Besides, your current path is the same",
				"Which way do you choose?\n\tGo straight (enter 7)\n\tTurn left (enter 8)\n"
			},
			{
				"WAIT",
				"You decide to continue squeezing yourself through the passageway. Thankfully, it returns to a normal-sized route not long after.\n\nNothing much occurs, and you find your fingers itching for your sword. Strange, how nothingness leads to more fear now. Even a time of peace makes you anxious.\n\nAt least, by the time you reach the next fork, nothing terrible has happened.\n\nThis time, there are signs labelling the two paths, though neither have words. On the left, there is a sign with a bunch of squiggly lines. A river perhaps? You are quite dehydrated. On the right, there is what looks suspiciously like a flower.",
				"Which path do you take?\n\tLeft (enter 9)\n\tRight (enter 10)\n"
			},
			{
				"WAIT",
				"You've had enough of the too-close walls, and you divert your route into the side path.\n\nWhich turns out to be a giant cave with nothing but moss, dripping stalactites and sharp stalagmites. You nearly trip over one. \n\nThere's nothing here. You can't even see a path. You turn back, and that is when you notice the small door across from you, hidden behind a lump of green. Using your sword, you cleave open the lock and crawl in.\n\nYour torch is so close to you that it's about to ignite your hair, and you're convinced that it's going to, until you reach an exit. There's an empty brazier, and you light it. Warmth and light explode into the desolate air.",
				"It's an actual hallway in a place that looks like it might've once been someone's home until a harpy came in and tore things up. All doors except two have been destroyed, and you peer into the empty rooms with much curiosity. Overturned furniture, scattered belongings, shredded papyrus. You pick up one piece that has intricate doodles on it. It looks suspiciously like a map.\n\nThe two remaining doors are locked. One is right at the end of the hall; it's quite massive, and has a strange mechanism padlocking it shut. The other is to the right of where you're standing, much smaller, and with a much less complicated looking lock that you could probably break with your sword.",
				"Which door do you go in?\n\tLarge door (enter 11)\n\tSmall door(enter 12)\n"
			},
			{
				"WAIT",
				"Your thirst prompts you to take a left, and the sound of water against rocks alerts you to the fact that there is, in fact, a river. It must be the one you crossed earlier.\n\nThe water still rushes violently, but this time, instead of being deep down in a canyon, it's moving by your feet. You drop to your knees and scoop up a handful of the clear liquid. The force of the flow nearly pulls you in, but you stay grounded.\n\nThe temperature of the water numbs your mouth and your taste, but it's the best thing you've had in some time. Unfortunately, there isn't a way for you to carry any for your journey, so you take in plenty of greedy gulps before tearing yourself away. You also properly clean the wounds that you've incurred during your bear fight and wash away some of the dirt on your body.",
				"Now hydrated, you continue alongside the banks until you reach a bend. The river flows to the right, but there is another, small path to the left. Sensibly, you continue to follow your water source, but something on the left catches your eye. There's a sort of metallic glint in the darkness, and it might be a useful tool in your final fight.",
				"What do you do?\n\tLook for the object (enter 13)\n\tFollow the river (enter 14)\n"
			},
			{
				"WAIT",
				"You ignore your thirst and the thought of potential water to investigate whatever this sign points to.\n\nLike depicted, it's a flower, or rather a patch of flowers. Or mushrooms. You don't know if flowers can grow in the darkness, though you're sure that there are flowers in the underworld.\n\nThey don't smell like anything, but they're pretty enough to look at. They're white and they kind of glow. You're not impulsive enough to eat them, though.",
				"Is it possible that these flowers have medicinal properties? Medicine was never your interest, and you kick yourself now for being stupid. If only you brought medical supplies here and not just a damn sword. It definitely would've fit under your tunic.\n\nIt's too late for regrets. You're one river, one door, and many forks in the path too late for regrets.\n\nWhatever, it'll be good to have these things on hand. Just in case. You pick a few and carry them with you. You hope they're not poisonous to the touch.",
				"Very soon, you're glad you finally relit your torch, because you arrive at a precipice leaning dangerously over...something too deep to see, but you don't want to find out. Without light, it would've been so easy to just fall. You laugh nervously at the thought.\n\nIt isn't a dead end though. There are two bridges: one to your left and one to your right, each leading into a set of tunnels. You shake both bridges rather vigorously, and they both look like they'll hold your weight. The only difference between them is that the bridge to your right has 1366 inscribed on the ground in front of it, while the bridge to your left reads 3149. You realize that there's words carved into the rock underneath your feet, and you bend down to dust it off.\n\nIt reads:\nThe farmer keeps chickens and rabbits, and has a total of 7654 livestock, amounting to 27884 legs. How many chickens does he keep?",
				"Which bridge do you take?\n\tThe bridge on the left (enter 15)\n\tThe bridge on the right (enter 16)\n"
			},
			{
				"END",
				"You pick up the lock of the large door in your hands and feel the cold metal warm in your grip. You carefully examine what appears to be a puzzle on the lock, and decide to give it a try.",
				"PUZZLE",
				"The lock snaps open, and the door begins to move on its own. You jump backwards as it leans outwards, groaning like a sleeping lion. Another loud door farther down the hall starts screeching, then another.\n\nYou're lost for a second. It takes a second for you to realize that the pain in your eyes is light, defeating the darkness and welcoming you back into the land of the living. You register that the sky outside is dark, though not as dark as the insides of that monster, but the moon is bright enough to make up for it.\n\nAfter the burning subsides, you notice that someone is standing on the other side. Hastily, you draw your sword, ready to engage in combat.\n\n\"Relax, young one. Put your sword down.\"\n\nYou don't. Vigilance is crucial. You still can't make out who this person is, but you aren't about to trust them.\n\n\"You've found the way out.\"",
				"You try to speak, but a scratchy gargle comes out. You realize you haven't drank water in a long, long time. The stranger notices, and offers you a drink. You're too thirsty to indulge your suspicions, and you down the entire supply of water within seconds.\n\n\"I was hoping that someone would make it here.\" The stranger grabs you by the arms to steady you before you can collapse, and you finally get to see his face. It's not one you recognize, but it's kind.\n\n\"I should never have made this beast,\" he sighs, before turning to face the shiny mass beneath his feet. You recognize that it's the ocean. \"I have prepared a ship for you to return home. I trust that you will not mention what happened to anyone you know?\"\n\nYou're a little too disoriented to fully comprehend what he's saying but you nod anyway. He smiles a bit, seemingly reassured. \"Good. Then go on your way now.\"",
				"Somehow, you end up on the ship he mentioned, and it's quite some time before you realize what you've done. You jump to your feet and stare at the disappearing shores, dizzy with shock over your entire experience. What happened doesn't feel real.\n\nBut it doesn't need to be, you think, as you stare at the outlines of mystical beasts in the stars, because you're going home. You wrap yourself tighter in bear fur and drift into peaceful sleep, a goodnight's rest for the journey ahead.",
				"THE END"
			},
			{
				"END",
				"With a swing of your sword, you crack open this lock as well, and the door creaks open. You slip into the place and set your torch on the wall.\n\nIt...looks like a bedroom.\n\nOf course, there aren't any windows, so perhaps it was a prison cell. Though you can't imagine prison cells with a bed that looks like it was once rather comfortable, or a nicely crafted desk.\n\nThere's a lot more papyrus scraps here, and even some complete sheets. You can't really understand them, but you leaf through them anyway. The intricate drawings of complicated mechanisms start to look more and more familiar?\n\nHuh, maybe the bridge you crossed before would've looked like that right after it was built. And aren't those the first set of doors you passed? Is that a sketch of a bear? \n\nWas this...the room of the inventor who built this?",
				"Unfortunately, you don't have much time to think this over, because the door somehow locks behind you.\n\nYou slam it with your hands, but there's no sign of others. It must've closed on its own. You try to pick the lock, but it doesn't yield.\n\nSo you're stuck here. Might as well sleep now that you have a comfortable bed. You'll solve this later.\n\nYou draw the moldy covers over your body, before deciding that maybe the bloody bear skin is the better option. You'll get out when you wake up, then search for water, which you desperately need now. Yeah, you can probably drink some from the stalactites. It'll be fine.\n\nYour rest is filled with strange dreams and feverish shouting. Your leg hurts somehow, and you try to recall when you injured it. You still feel a portion of your mind thinking about what to do when you wake up.\n\nYou never do.",
				"THE END"
			},
			{
				"END",
				"It doesn't take long to find what caught your eye, and you brim with anticipation.\n\nThere's a sword jammed in a wall, and by the looks of it, a good one. The sword you carry with you is a bit smaller than you'd prefer, mostly to hide it when you entered, but this one is different. It looks heavy and sharp, perfect for a fight with some sort of bullheaded monster.\n\nExcited over some long-awaited good news, you reach out and pull. \n\nIt strikes you a second too late that it may be a trap.",
				"The walls start crumbling.\n\nStones tumble around the hole the sword was in, and you stumble backwards. Rocks and boulders fly loose from their places. You feel a jolting pain in your leg, and then nothing. Heavy weights pile on your chest, pressing harder and harder against your ribs.\n\nAnd once again, you are wrapped in darkness.",
				"THE END"
			},
			{
				"WAIT",
				"The river continues downstream, and so do you. You wonder if there are fish inside you could catch, or where this river came from and where it goes. Maybe if you keep following it, you'll know the answer.\n\nThis time, the split is of the river itself. It branches off into two streams: wider and furious on the left, and barely a docile trickle on the right.",
				"Which side do you follow?\n\tGo left (enter 17)\n\tGo right (enter 18)\n"
			},
			{
				"WAIT",
				"After some deliberation, you walk the bridge to your left. It creaks dangerously, but it holds. You release your breath once you step on solid land again.\n\nUnfortunately for you, it's not the last time you'll be hovering in the air. Looks can be deceiving; what happened to just a short bridge and then a tunnel?\n\nNow, you have another set of bridges to choose between. The one in front of you is another dingy  hanging rope bridge, like the one you took before. The other, to your left is built of solid planks,, but some have already decayed. Both stretch over drops that you would prefer not to fall into.",
				"Which bridge do you take?\n\tRope bridge (enter 19)\n\tPlank bridge (enter 20)\n"
			},
			{
				"WAIT",
				"After some deliberation, you walk the bridge to your right. It's a bit wobbly, but nothing else happens. You hurry away from the cliff and continue your walk.\n\nYour foot kicks something hard before your eyes can spot it. You lower your torch for inspection, and immediately regret the decision.\n\nIt's a corpse, and from the looks of it, their death wasn't peaceful, nor was it recent.\n\nThe fear that had been chased away by your endless wandering and pain returns. If you don't win, this could be your fate.",
				"Fate leads you to another crossroads soon enough. You can't see much difference between your two choices, but you do smell something strange on the right. It's a bit metallic. When you head towards the left, it just feels a bit colder.",
				"What do you do next?\n\tTurn left (enter 21)\n\tTurn right (enter 22)\n"
			},
			{
				"END",
				"You've been walking for quite some time now, but with a constant source of water, you're not as tired as you were before. You let the river be your guide, and you slip into a sort of resting state of mind. All you have to do is conquer the sometimes rough terrain that accompanies the stream.\n\nThe river broadens, then widens, and the roaring of the bull dims. You laugh a little at your comparison. Does that mean the river moos like a cow now?\n\nAlas, with how much different it is from the stampeding rush when you first encountered it, you wouldn't even know it was the same river.\n\nBut why is it slowing so much?",
				"Your footsteps halt suddenly, like the movement of the river, as a possibility trickles into your mind.\n\nIs the river nearing its mouth?\n\nYou push yourself forwards. Does this mean that you've found an exit?\n\nYou taste salt in your mouth, and you wonder when you've grown so soft that the thought of escape makes you cry. What about fighting the beast?\n\nBut you're not crying.",
				"It's the ocean breeze, and it's stinging your skin with fresh scores of salt.\n\nAnd now you are crying, as the sound of birds and the streams of light begin to overwhelm you.\n\nThe thought of eternal glory by defeating the monster won't make you go back. Nothing can push you back into those dark tunnels. How can there be any monster worse than the one that has already swallowed the youth of your land?\n\nThe green of the island comes into view, and without hesitation, you dive into the river, in case any guards are outside. There don't seem to be any, though, and you sprawl yourself onto dry land once you're sufficiently far from the gloomy stone complex, and the water begins to sting your eyes.\n\nPale flushes of light colour the sky as Eos creeps over the horizon. You laugh as warmth spills onto the ground, and you've never been so grateful for the sun.\n\nWho needs to be a hero when there's so much left to live for?",
				"THE END"
			},
			{
				"END",
				"It isn't long before the stream tapers away, and the movement of the world once again fades into stillness. \n\nYou feel more alone than ever.\n\nSo really, it's a relief when you spot a flurry of movement in the corner, like the flapping of wings. Curious, you lift your torch towards the shadows.\n\nHundreds of what look like birds dive towards you, swarming like bees in the air. You feel soft feathers and sharp claws on your skin. Your arms flail as you try to bat them away. Somewhere in the scuffle, your torch falls.\n\nTufts of bear fur, tufts of your hair, talonfuls of your tunic; pieces of everything fly to the floor. You pick up your pace, but the animals form a solid mass you can't break through. \n\nYou feel your feet sliding against the floor. But you're not the one moving, they are.\n\nThere's thousands of tiny pincers digging into your skin, and you're dragged through the low tunnels of this winding mess.\n\nTo where, you're not sure, because you pass out to the sound of frantically beating wings.",
				"THE END"
			},
			{
				"END",
				"You hold your breath and cross the rope bridge, trying to spread your weight as much as possible.\n\nIt works. You make it safely across, though it felt like you walked the entire length of a city.\n\nYou couldn't see what was on this side from where you were, and the dive into the darkness was unsettling, but looking at it now, there's nothing to be afraid of on this side.\n\nIt's just another empty hallway. \n\nUntil it isn't.",
				"You don't know what sort of trap you've sprung, until a faint clicking draws your attention.\n\nAnd by then, it's too late.\n\nProjectiles spring from the walls and embed into you, merging into your life with painful stings.\n\nYou meet your end like the game, instead of the hunter.",
				"THE END"
			},
			{
				"END",
				"Despite the gaps in its structure, the plank bridge looks much sturdier, despite its missing parts. You decide to risk it.\n\nYou take ginger steps, resting only half your weight on each plank, stomping it hard to ensure it doesn't break, before you cross. After a few, you deduce that the bridge is safe.\n\nUnfortunately, you never quite learned the saying \"never judge a book by its cover.\"",
				"You don't test the next plank you step on, and immediately regret it when it begins to crack. Before you can react, it gives away under your feet.\n\nYour weight falls through. You manage to grab hold of the plank next to it, the one that you were standing on, but it breaks as well.\n\nThe sensation of falling takes over your thoughts, but not before you manage to process what exactly is about to happen.",
				"THE END"
			},
			{
				"END",
				"The path to the left begins to slope downwards as you venture further, eventually turning into roughly carved stairs. And it gets very, very cold. You pull the bear fur closer in an attempt to preserve your heat, and make sure your hands are warmed by your dwindling torch.\n\nYou think of turning back, like the many times you've thought so before, but you move on. There's no time for regret.\n\nUntil it's too late of course, but you haven't reached that point yet.",
				"The air grows colder and colder, and you begin to shiver. What is even in here?\n\nYour torch finally gives way, and even though its heat was minimal, the frigidity of the air becomes apparent immediately.\n\nThankfully, the cold wears away, but then it becomes excruciatingly hot. You toss away your bulky bear fur, and eventually it gets so hot you need to strip away your tunic. It wasn't even this hot when you were standing directly under the summer sun.\n\nYou're definitely still afraid though. As before, you've plunged into darkness once again, and it's not comfortable. \n\nStrange. Usually when you're scared, you can feel your heart drumming away in your chest. Not today though, it seems.\n\nYou blackout without realizing the temperature has only gotten colder.",
				"THE END"
			},
			{
				"WAIT",
				"A little nauseous from your discovery, you continue on the path to the right. You don't last long, however, before you trip over yourself, disoriented.\n\nThe complaints of your stomach cues you in to the reason.\n\nYou realize that you're really, really hungry. The bear meat was filling while it lasted, but a lot of time must've passed since then. You feel dizzy, weak, like all the strength in your body has been sapped away.\n\nYou do have one food source, but...",
				"You glance at the flower-mushrooms in your hand. They don't look like what you'd expect a poisonous thing to, and there are plenty of stories of mystical plants with mystical properties. Though, since this maze was man-made, that is deemed unlikely in your eyes.\n\nNonetheless, you can feel that you're about to pass out, and taking a risk is better than doing nothing. You tear up a piece of one plant and eat it.\n\nIt doesn't taste bad, which is a good sign, and you eat the rest of your stock. You lean against a wall to rest.",
				"Surprisingly, you begin feeling much better, like you'd eaten a proper meal. Maybe these things were actually medicinal. You find the strength to get up and move again.\n\nAs you run your fingers along the wall, you feel something that makes you jolt: something sticky, like blood.\n\nYour experience with the corpse from before has made you jumpy. Are you nearing the center? You pause to investigate.",
				"Soon, you notice scratches on the wall, like they were made with a weapon. You shudder as you remind yourself that you are not the first to make an attempt. \n\nThere are more scratches, on the floors and walls and ceiling, as you move ahead, but there's also something else: more splatters of blood, most of which lead into a path going to the right. It's entirely possible that the beast resides there, and a valiant warrior had once fought between those very walls.\n\nYou just know it; you're getting closer. Every step you take from now is crucial.",
				"Do you continue forward, on this path with scratches, or do you turn right, towards the path with blood?\n\tGo straight (enter 23)\n\tTurn right (enter 24)\n"
			},
			{
				"END",
				"Something finally comes into view, and with a sinking feeling, you realize what it is.\n\nIs this it? Your final trial?\n\nThere's a massive room, lit with columns of fire, and in the centre sleeps a beast that makes the entire place look small. The head of a bull rests upon the body of a man who would be twice your stature. \n\nYou gulp back any inhibitions; this is the final battle.\n\nLife or death.\n\nYour footsteps echo too loud in the silent space, and the beast stirs. It's eyes flutter open, then fixate on a single spot.\n\nYou.\n\nYou draw your sword, and ready yourself for the battle.",
				"Your leg is still in pain from the bear fight, but you will yourself to jump higher, run faster. The beast roars, a language that sounds like yours, but much more garbled.\n\n\"Wait, I-,\" But it doesn't want to reason with you. It lifts a stone pillar and hurls it at your feet. You leap backwards, then charge forwards. Your sword flashes in your arms.\n\nIt's unlike anything you've done before; the energy that surges through you doesn't even feel like your own, but you wield it like you've been trained. It isn't long before blood is drawn, and you land your first strike on the beast.",
				"The battle drags on. You have a moment where you think that perhaps if you survive to tell the tale, you'd say it lasted an entire day.\n\nIt may not be true, but it certainly feels that way.\n\nThe beast fights well, but you fight better, to the surprise of you both. Though you are definitely no match for its strength. It misses a punch, and its fist slams into a pillar. You dodge the collapsing rocks.\n\nYour size makes you much more agile and fast. You need to use it to your advantage.",
				"You leap behind a pile of boulders and sneak to a different position, allowing for a surprise attack on the monster. That's how it loses an arm.\n\nThe growling rage that follows causes you to retreat behind another mass. It swings at you, and you run again. \n\nIt's too tiring to continue like this. You need a quick finish.\n\nThere's a mantra of yours that has proved true again and again: when in doubt, burn things. You recall your fight with the bear.\n\nIt might not work, but there's still a chance, compared to this battle of stamina.\n\nLike before, you grab your torch and launch it like a javelin. It swats it off, annoyed, probably proud of itself for having thwarted your brilliant fight.\n\nBut that's not the end of it.",
				"You muster up the rest of your strength and grab a brazier, suppressing your own curiosities over how it's still burning. With a shout, you haul it at your unsuspecting target.\n\nAnd like before, you grab at the opportunity like a deadly predator.\n\nThe sword lodges right in the chest of your opponent. Using your remaining energy, you twist it deep into its cavity.\n\n\"NO!\" It yells in pain, and you lurch backwards in horror at a realization.\n\nIt speaks. Like you.",
				"He falls to the ground, and the foundations shake. You fall as well, before you remember that only one of you can leave. You scamper forward, and pull your sword from thick muscle.\n\n\"Is this it?\" He speaks his last words with a somber tone. He stirs, slick blood running down its chest, before falling still, accepting his fate.\n\n\"I do what I must.\" With one swing, you sever his head, the final prize you must claim.",
				"There is no way out. You can't remember the way you took. \n\nIs everything really over? You sprawl yourself over the cold floor. Blood, no longer warm, stains your clothing.\n\nOnce again, the room falls silent. You strain your ears for a sign that you're not alone in this damp world.\n\nThat's when you hear the rush of water.\n\nYou haul the head by its horns as you investigate the source of the sound.\n\nIt's the river, and it cuts through a corner of the room. There's a small path carved beside it, covered roughly with boulders to disguise it. You pull them away to reveal your saving grace.",
				"The head is a heavier burden than fear, though the latter no longer consumes you. The torrential roar of the river slows and calms, then silences as you near the light of the living.\n\nYou've made it out.\n\nThe sun beats down like it did when you entered, but it doesn't hurt in the same way. Everything feels like it's been polished, and everything feels beautiful.\n\nThere's no better feeling than life after you've brushed death, though the happiness suffocates you. You stare at the head in your hands and hesitate.\n\nYou let the warm sun blanket your body for a moment, before setting off towards the city, the foreboding stone caverns bidding you farewell.",
				"THE END"
			},
			{
				"WAIT",
				"You desperately want to know where the blood is from. The curiosity burns in you, and you take the path to the right.\n\nIt's exactly what you wanted to find, but also not what you wanted to find.\n\nThe corpse in question for this time is one you recognize: it's one of the girls that were sent with you. Your reaction is much stronger this time, and there's a bitter taste in your mouth before you realize it. Your last meal is emptied onto the floors. It's somehow less revolting than her remains.\n\nYou gulp back the heave that comes next. You're having extreme regrets about taking this path.",
				"You hurry away from the body as fast as you can, with your sword drawn to attack whatever did that to her, though you already have a faint idea.\n\nNo, you won't be like her. You won't end up like her. You WILL survive and avenge her.\n\nYou push away memories of conversations and laughter aboard a doomed ship. You turn back to look at where you came from, and continue on your doomed journey towards whatever lies ahead.",
				"Your torch goes out just as you reach what could very well be your final crossroads. It's a shame that you don't get to examine either path. You feel around with your fingers, blind and helpless in strange territories once again. The path on the left seems to make a very sharp turn not far from where you came from, while the one on the right seems to wind a bit but not dramatically.",
				"What is your next move?\n\tTurn left (enter 25)\n\tTurn right (enter 26)\n"
			},
			{
				"END",
				"You walk the path to the left and hope for the best. You keep your footsteps as silent as possible, afraid of alerting the monster that could be ahead. You use your sword to feel your path.\n\nAnd then you hear it.\n\nSoft grunting, and it's coming from...\n\nBehind you???",
				"You whirl around with your sword, but the beast has already made its move. Pain shoots up your leg, but you slash your blade, and the monster retreats with an angry growl.\n\nYou fight with everything: desperation, anger, courage, fear. Both sides manage to land strikes. The metallic smell of blood grows stronger, and you wonder if whoever comes next will notice this grisly scene.\n\nBlind, hungry, thirsty, tired. How cruel it is that you come this far to end up in an unfair fight, you think, before you're slammed into a silent darkness.",
				"THE END"
			},
			{
				"END",
				"This path is more winding than the rest. It twists and turns like a snake, so much you become dizzy.\n\nWhere are you? It's been so long. Desperation continues to dig at your bones. You begin counting seconds.\n\nOne. Two. Five. Twenty. Sixty seven. Four hundred forty one. Nine thousand eighty six. Three hundred seventy one thousand eight hundred fifty three.\n\nSurely you're counting too fast.\n\nThe wounds you sustained from your bear fight bothered you at first, but the sensations have begun to fade away. Everything is fading away. For such a cold place, you're strangely warm, from head to toe.\n\nYou press a hand to your forehead. It's sweating, strangely. So strange.",
				"Four hundred thousand. Four hundred thousand one. Four hundred thousand one hundred. Four hundred thousand eighty two. Four zero zero eight three. Four zero zero zero eight four.\n\nIt's strange to not feel your limbs.\n\nForty thousand one hundred ten. Forty thousand two hundred ten.\n\nHow are you getting dizzy from walking? You feel a bit silly wobbling around. It makes you chuckle.\n\nFour thousand four hundred forty one. Four hundred forty two. \n\nYour legs feel woozy.\n\nForty three. Four. Zero.\n\nYou pass out against the stone walls.",
				"THE END"
			}
		};
	static boolean globAdj[][] = 
		{
			{false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
		};
}
